# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hV5FjEdms_jOD8f57dBOfu10r2MX6Ein
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.linear_model import LinearRegression

df = pd.read_excel('RIDGE.xlsx')

df.head(6)

X = df.iloc[:, :-1]
y = df.iloc[:,-1]

regressor = LinearRegression()

regressor.fit(X, y)

import pickle

pickle.dump(regressor, open('model.pkl','wb'))

